name: Build Nugets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Versions
      env:
        VERSION_PREFIX: '0.20'
        VERSION_SUFFIX: ${{github.run_number}}
      run: |
        VERSION=$VERSION_PREFIX.$VERSION_SUFFIX
        sed -i bak "s:<Version>1.0.0</Version>:<Version>$VERSION</Version>:g" CLanguage/CLanguage.csproj
        sed -i bak "s:<version>1.0.0</version>:<version>$VERSION</version>:g" CLanguage.Editor.nuspec
        sed -i bak2 "s:version=\"1.0.0\":version=\"$VERSION\":g" CLanguage.Editor.nuspec
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.300
    - name: Install dependencies
      run: msbuild /t:Restore /p:Configuration=Release CLanguage.sln
    - name: Build
      run: dotnet build -c Release CLanguage/CLanguage.csproj
    - name: Test
      run: dotnet test -c Release CLanguageTests/CLanguageTests.csproj
    - name: Build iOS Test
      run: msbuild /p:Configuration=Release CLanguageTestsiOS/CLanguageTestsiOS.csproj
    - name: Build Mac Editor
      run: msbuild /p:Configuration=Release Editor/Mac/CLanguage.Editor.Mac.csproj
    - name: Build iOS Editor
      run: msbuild /p:Configuration=Release Editor/iOS/CLanguage.Editor.iOS.csproj
    - name: Package Library
      if: github.event_name == 'push'
      run: |
        mkdir PackageOut
        cd CLanguage && dotnet pack --include-symbols --no-build -c Release -v normal -o ../PackageOut
    - name: Package Editor
      if: github.event_name == 'push'
      run: |
        nuget pack CLanguage.Editor.nuspec -OutputDirectory PackageOut
    - name: Package
      if: github.event_name == 'push'
      uses: actions/upload-artifact@master
      with:
        path: PackageOut
